#!/usr/bin/env bash


unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)
      script=rofi -p " Key" -i -dmenu "$@"
      shopt -s nullglob globstar
      ;;
    Darwin*)
      script=fzf
      shopt -s nullglob
      ;;
    *) exit;;
esac

export LANG="en_US.UTF-8" 
typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | $script )

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
	pass show -c "$password" 2>/dev/null
else
	pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } |
		xdotool type --clearmodifiers --file -
fi
